### ISSUE TITLE
Nginx container is "unhealthy" when redirect rules are set up

### ISSUE THREAD

**Issue by achekulaev** [docksal/service-nginx#2]
When redirect rules are set up in overrides, healthcheck not always can reach `/.healthz` and Docker deems container unhealthy. See https://github.com/docksal/docksal/issues/1127 for details. 

Heathcheck approach should be revised.

**Comment by lmakarov** [comment]
@achekulaev can you provide an example config that causes this issue?

**Comment by achekulaev** [comment]
@lmakarov see docksal/docksal#1127 but basically I'd imagine anything that misconfigures the routing, but keeps server alive

**Comment by lmakarov** [comment]
Closing in favor of https://github.com/docksal/service-nginx/issues/5, since that one has the context.
